In [61]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [45]:
p_zip = pd.read_csv("HomePrice_ZipCode.csv")

C:\Users\Amber\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (246,248) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [46]:
p_zip.head()

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12
0,84654.0,60657.0,Chicago,IL,Chicago,Cook,1.0,420800.0,423500.0,426200.0,...,1087500.0,1080200.0,1073700.0,1064100.0,1052600.0,1047600.0,1047700.0,1047600.0,1048800.0,1051600.0
1,84616.0,60614.0,Chicago,IL,Chicago,Cook,2.0,542400.0,546700.0,551700.0,...,1526300.0,1527000.0,1524600.0,1516600.0,1512500.0,1513700.0,1513600.0,1508100.0,1502300.0,1496300.0
2,93144.0,79936.0,El Paso,TX,El Paso,El Paso,3.0,70900.0,71200.0,71100.0,...,114000.0,113800.0,114000.0,114000.0,113800.0,113700.0,114200.0,114300.0,114000.0,114000.0
3,84640.0,60640.0,Chicago,IL,Chicago,Cook,4.0,298200.0,297400.0,295300.0,...,735700.0,728400.0,726800.0,724900.0,717200.0,709400.0,707700.0,708300.0,704800.0,700900.0
4,61807.0,10467.0,New York,NY,New York,Bronx,5.0,NaN,NaN,NaN,...,392700.0,396300.0,399100.0,401000.0,403100.0,405200.0,407600.0,408800.0,409600.0,410500.0

In [47]:
p_zipdrop = p_zip.drop(['City', 'RegionName', 'State', 'Metro', 'CountyName', 'SizeRank'], axis=1)

In [48]:
T_pzip = p_zipdrop.set_index('RegionID').T

In [49]:
T_pzip.tail(10)

RegionID,84654.0,84616.0,93144.0,84640.0,61807.0,91733.0,97564.0,90668.0,62037.0,91940.0,...,81927.0,99032.0,62697.0,58333.0,99074.0,73940.0,59107.0,66881.0,94815.0,nan
2017-03,1.0875e+06,1.5263e+06,114000,735700,392700,154700,3.9121e+06,313300,932200,155700,...,145100,317700,104700,216000,633400,550500,183600,761000,187500,NaN
2017-04,1.0802e+06,1.527e+06,113800,728400,396300,155600,3.9122e+06,315600,934700,156900,...,143200,316200,106600,217900,621000,563900,182800,762300,187600,NaN
2017-05,1.0737e+06,1.5246e+06,114000,726800,399100,158700,3.9223e+06,317800,935300,159600,...,140800,317800,108100,219200,611300,565300,183400,770500,187200,NaN
2017-06,1.0641e+06,1.5166e+06,114000,724900,401000,160700,3.9595e+06,318600,935200,161300,...,140400,322700,108600,220000,601900,565500,186200,777900,188200,NaN
2017-07,1.0526e+06,1.5125e+06,113800,717200,403100,161300,3.9815e+06,318400,933100,162300,...,142300,327600,108800,220100,604700,563700,189000,780700,190400,NaN
2017-08,1.0476e+06,1.5137e+06,113700,709400,405200,162500,3.9534e+06,319100,921100,163900,...,144500,332500,109400,220200,618700,554400,190300,776800,192700,NaN
2017-09,1.0477e+06,1.5136e+06,114200,707700,407600,164000,3.8946e+06,322100,914000,165300,...,146400,336600,109800,221200,627100,544800,191000,772300,194100,NaN
2017-10,1.0476e+06,1.5081e+06,114300,708300,408800,164400,3.896e+06,324600,919700,166400,...,146700,336100,111000,222200,630900,538500,191300,772200,194700,NaN
2017-11,1.0488e+06,1.5023e+06,114000,704800,409600,164200,3.9526e+06,325300,933000,168300,...,145700,333100,113400,223700,635800,539500,191600,772400,193400,NaN
2017-12,1.0516e+06,1.4963e+06,114000,700900,410500,164000,4.007e+06,324900,940100,170200,...,144700,331800,115800,225400,640900,542900,192800,765700,191100,NaN

In [56]:
T_pzip.index = pd.to_datetime(T_pzip.index)

In [57]:
T_pzip.head(10)

RegionID,84654.0,84616.0,93144.0,84640.0,61807.0,91733.0,97564.0,90668.0,62037.0,91940.0,...,81927.0,99032.0,62697.0,58333.0,99074.0,73940.0,59107.0,66881.0,94815.0,nan
1996-04-01,420800,542400,70900,298200,NaN,76700,NaN,NaN,NaN,72300,...,201000,146900,68300,98900,NaN,NaN,86700,253500,NaN,NaN
1996-05-01,423500,546700,71200,297400,NaN,76500,NaN,NaN,NaN,72400,...,200900,145300,67900,98100,NaN,NaN,87500,254000,NaN,NaN
1996-06-01,426200,551700,71100,295300,NaN,76000,NaN,NaN,NaN,72000,...,201000,144900,69800,97800,NaN,NaN,88100,255300,NaN,NaN
1996-07-01,428600,565000,71300,294600,NaN,75800,NaN,NaN,NaN,71600,...,201000,145100,70500,97600,NaN,NaN,86700,258200,NaN,NaN
1996-08-01,429900,574200,71400,295700,NaN,75700,NaN,NaN,NaN,71300,...,200900,145900,67000,96900,NaN,NaN,84400,261000,NaN,NaN
1996-09-01,432300,581700,71900,296500,NaN,75600,NaN,NaN,NaN,71100,...,200900,146800,62100,96400,NaN,NaN,82600,263400,NaN,NaN
1996-10-01,436400,591500,72700,296300,NaN,75700,NaN,NaN,NaN,70700,...,200900,146600,60100,96000,NaN,NaN,81400,267000,NaN,NaN
1996-11-01,435600,591200,73100,294300,NaN,75900,NaN,NaN,NaN,70600,...,201000,145500,59400,96100,NaN,NaN,80400,274800,NaN,NaN
1996-12-01,427400,581100,72700,291000,NaN,76100,NaN,NaN,NaN,71000,...,201000,145700,59500,96600,NaN,NaN,79000,282300,NaN,NaN
1997-01-01,421600,575100,72700,288100,NaN,76600,NaN,153600,NaN,71600,...,201000,146900,59700,97000,NaN,NaN,77500,285700,NaN,NaN

In [58]:
import seaborn as sb
# seaborn the dataviz api to use
%matplotlib inline
import matplotlib.pyplot as plt

In [76]:
T_pzip.astype(float)

ValueError: could not convert string to float: +/-97

In [64]:
T_pzip['Total']=T_pzip.sum()

In [65]:
T_pzip.head()

RegionID,84654.0,84616.0,93144.0,84640.0,61807.0,91733.0,97564.0,90668.0,62037.0,91940.0,...,99032.0,62697.0,58333.0,99074.0,73940.0,59107.0,66881.0,94815.0,nan,Total
1996-04-01,420800,542400,70900,298200,NaN,76700,NaN,NaN,NaN,72300,...,146900,68300,98900,NaN,NaN,86700,253500,NaN,NaN,NaN
1996-05-01,423500,546700,71200,297400,NaN,76500,NaN,NaN,NaN,72400,...,145300,67900,98100,NaN,NaN,87500,254000,NaN,NaN,NaN
1996-06-01,426200,551700,71100,295300,NaN,76000,NaN,NaN,NaN,72000,...,144900,69800,97800,NaN,NaN,88100,255300,NaN,NaN,NaN
1996-07-01,428600,565000,71300,294600,NaN,75800,NaN,NaN,NaN,71600,...,145100,70500,97600,NaN,NaN,86700,258200,NaN,NaN,NaN
1996-08-01,429900,574200,71400,295700,NaN,75700,NaN,NaN,NaN,71300,...,145900,67000,96900,NaN,NaN,84400,261000,NaN,NaN,NaN

In [59]:
T_pzip.resample('M').sum().plot()

ValueError: Image size of 395x200740 pixels is too large. It must be less than 2^16 in each direction.